version: "3.9"

services:
  paganini-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paganini-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - paganini-network

networks:
  paganini-network:
    driver: bridge
